#!/usr/bin/env bash

#shutdown
pgrep -f "python ./site" | xargs kill > /dev/null
screen -S moxws -X quit

#application
sleep 1
spawn-fcgi -f ./site.py -p 9666
#websocket server
screen -dmS moxws python3.4 sockets.py
